"""
Export trained nanoGPT checkpoint to a C header file with int8 quantized weights.
Usage: uv run python export/export_weights.py
"""
import torch
import numpy as np
import os
import pickle

CKPT_PATH = "nanoGPT/out-micro/ckpt.pt"
META_PATH = "nanoGPT/data/shakespeare_char/meta.pkl"
OUT_PATH  = "export/weights.h"

def quantize_per_channel_int8(tensor):
    """
    Per-output-channel symmetric int8 quantization.
    For a (out_dim, in_dim) weight matrix, computes one scale per row.
    Returns (int8 array shape (out_dim, in_dim), scales array shape (out_dim,))
    Dequant: float_val[o, i] = int8_val[o, i] * scales[o]
    """
    t = tensor.detach().cpu().numpy().astype(np.float32)
    if t.ndim == 1:
        # 1D tensor — fall back to per-tensor
        max_abs = np.max(np.abs(t))
        if max_abs == 0:
            return np.zeros_like(t, dtype=np.int8), np.array([1.0], dtype=np.float32)
        scale = max_abs / 127.0
        q = np.round(t / scale).clip(-127, 127).astype(np.int8)
        return q, np.array([scale], dtype=np.float32)
    # 2D: (out_dim, in_dim), one scale per row
    out_dim = t.shape[0]
    scales = np.zeros(out_dim, dtype=np.float32)
    q = np.zeros_like(t, dtype=np.int8)
    for o in range(out_dim):
        row = t[o]
        max_abs = np.max(np.abs(row))
        if max_abs == 0:
            scales[o] = 1.0
            continue
        scales[o] = max_abs / 127.0
        q[o] = np.round(row / scales[o]).clip(-127, 127).astype(np.int8)
    return q, scales

def write_int8_array_pc(f, name, arr, scales, shape_comment):
    """Write int8 array + per-channel scale array."""
    flat = arr.flatten()
    f.write(f"// {name}: shape {shape_comment}, per-channel scales\n")
    f.write(f"const int8_t {name}[{len(flat)}] = {{\n")
    for i in range(0, len(flat), 16):
        chunk = flat[i:i+16]
        line = ", ".join(f"{int(v):4d}" for v in chunk)
        f.write(f"    {line},\n")
    f.write("};\n")
    f.write(f"const float {name}_scales[{len(scales)}] = {{\n    ")
    for i, s in enumerate(scales):
        f.write(f"{s:.8f}f, ")
        if (i + 1) % 6 == 0:
            f.write("\n    ")
    f.write("\n};\n\n")

def main():
    print(f"Loading checkpoint from {CKPT_PATH}")
    ckpt = torch.load(CKPT_PATH, map_location="cpu", weights_only=False)
    model_args = ckpt["model_args"]
    state = ckpt["model"]

    # Strip "_orig_mod." prefix if torch.compile was used
    state = {k.replace("_orig_mod.", ""): v for k, v in state.items()}

    print("Model config:")
    for k, v in model_args.items():
        print(f"  {k}: {v}")

    with open(META_PATH, "rb") as mf:
        meta = pickle.load(mf)
    vocab_size = meta["vocab_size"]
    itos = meta["itos"]

    n_layer = model_args["n_layer"]
    n_head  = model_args["n_head"]
    n_embd  = model_args["n_embd"]
    block_size = model_args["block_size"]

    os.makedirs("export", exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("// Auto-generated by export_weights.py\n")
        f.write("// Tiny GPT weights, int8 symmetric per-channel quantization\n\n")
        f.write("#ifndef WEIGHTS_H\n#define WEIGHTS_H\n\n")
        f.write("#include <stdint.h>\n\n")

        f.write(f"#define VOCAB_SIZE   {vocab_size}\n")
        f.write(f"#define N_LAYER      {n_layer}\n")
        f.write(f"#define N_HEAD       {n_head}\n")
        f.write(f"#define N_EMBD       {n_embd}\n")
        f.write(f"#define HEAD_DIM     {n_embd // n_head}\n")
        f.write(f"#define BLOCK_SIZE   {block_size}\n\n")

        # Vocab table — for decoding token IDs back to characters
        f.write(f"const char vocab[{vocab_size}] = {{\n    ")
        for i in range(vocab_size):
            c = itos[i]
            if c == '\\': lit = "'\\\\'"
            elif c == "'": lit = "'\\''"
            elif c == '\n': lit = "'\\n'"
            elif c == '\t': lit = "'\\t'"
            elif c == '\r': lit = "'\\r'"
            elif 32 <= ord(c) < 127: lit = f"'{c}'"
            else: lit = f"{ord(c)}"
            f.write(lit + ", ")
            if (i + 1) % 12 == 0: f.write("\n    ")
        f.write("\n};\n\n")

        # Embeddings
        wte, scales = quantize_per_channel_int8(state["transformer.wte.weight"])
        write_int8_array_pc(f, "wte", wte, scales, f"({vocab_size}, {n_embd})")

        wpe, scales = quantize_per_channel_int8(state["transformer.wpe.weight"])
        write_int8_array_pc(f, "wpe", wpe, scales, f"({block_size}, {n_embd})")

        # Per-layer weights
        for i in range(n_layer):
            p = f"transformer.h.{i}."

            # LayerNorm 1 — keep as float, it's tiny
            ln1_w = state[p + "ln_1.weight"].detach().cpu().numpy().astype(np.float32)
            f.write(f"const float ln1_w_{i}[{n_embd}] = {{ ")
            f.write(", ".join(f"{v:.6f}f" for v in ln1_w))
            f.write(" };\n")

            # Attention QKV (combined) and output projection
            qkv, scales = quantize_per_channel_int8(state[p + "attn.c_attn.weight"])
            write_int8_array_pc(f, f"attn_qkv_w_{i}", qkv, scales, f"({3*n_embd}, {n_embd})")

            attn_proj, scales = quantize_per_channel_int8(state[p + "attn.c_proj.weight"])
            write_int8_array_pc(f, f"attn_proj_w_{i}", attn_proj, scales, f"({n_embd}, {n_embd})")

            # LayerNorm 2
            ln2_w = state[p + "ln_2.weight"].detach().cpu().numpy().astype(np.float32)
            f.write(f"const float ln2_w_{i}[{n_embd}] = {{ ")
            f.write(", ".join(f"{v:.6f}f" for v in ln2_w))
            f.write(" };\n")

            # FFN
            fc, scales = quantize_per_channel_int8(state[p + "mlp.c_fc.weight"])
            write_int8_array_pc(f, f"mlp_fc_w_{i}", fc, scales, f"({4*n_embd}, {n_embd})")

            proj, scales = quantize_per_channel_int8(state[p + "mlp.c_proj.weight"])
            write_int8_array_pc(f, f"mlp_proj_w_{i}", proj, scales, f"({n_embd}, {4*n_embd})")

        # Final layer norm
        lnf_w = state["transformer.ln_f.weight"].detach().cpu().numpy().astype(np.float32)
        f.write(f"const float lnf_w[{n_embd}] = {{ ")
        f.write(", ".join(f"{v:.6f}f" for v in lnf_w))
        f.write(" };\n\n")

        f.write("#endif // WEIGHTS_H\n")

    size_bytes = os.path.getsize(OUT_PATH)
    print(f"\nWrote {OUT_PATH} ({size_bytes/1024:.1f} KB of source)")

    # Estimate flash footprint of the actual int8 data
    total_int8_params = (
        vocab_size * n_embd                    # wte
        + block_size * n_embd                  # wpe
        + n_layer * (
            3 * n_embd * n_embd                # attn qkv
            + n_embd * n_embd                  # attn proj
            + 4 * n_embd * n_embd              # mlp fc
            + 4 * n_embd * n_embd              # mlp proj
        )
    )
    print(f"Estimated int8 weight footprint: {total_int8_params/1024:.1f} KB")
    print(f"Plus float layer norms: ~{(n_layer*2 + 1) * n_embd * 4 / 1024:.1f} KB")

if __name__ == "__main__":
    main()